baseURL = "https://nolacon.github.io/"
# site-nolacon-2022/"
canonifyURLs = true
languageCode = "en-us"
title = "Nolacon"
theme = "nolacon-theme-hugo"


# Params

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params]
    title = "Nolacon 2019"
    date = "2019-05-17"
    description = "The DevFest, or 'Developers Festival', is a technical conference for developers. It is aimed at students, professionals or simply curious technophiles."
    images = ["/images/social-share.jpg"]
    email = "contact@nolacon.com"
    keywords = "event, gdg, gde, devfest, google, programming, android, chrome, developers, web, cloud, androiddev"
    copyright = "We :heart:️ chocolatines"

    cfpUrl = "https://conference-hall.io/public/event/HJRThubF4uYPkb7jSUxi"

    # email subscription url
    subscriptionUrl = "https://nolacon.us3.list-manage.com/subscribe/post?u=cc1ef3ee95024f9bf3ce37df1&id=94ee29ea76"
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"
    googleWebmasterKey = "BcIJYWDHoblML5DO66_b1BGBne9J_7Oq3GjC5SDCKK8"

[params.logos]
    jumbo = "/images/logos/jumbo.png"
    header = "/images/logos/header.png"
    footer = "/images/logos/header.png"

[menu]
[[menu.main]]
    identifier = "call-for-papers"
    name = "CFP"
    url = "https://jobs.devfesttoulouse.fr/"
    weight = 300
    external = true

#[[menu.main]]
#    identifier = "jobs"
#    name = "Jobs"
#    url = "https://jobs.devfesttoulouse.fr/"
#    weight = 200
#    external = false

#[languages]
#[languages.en]
#    weight = 1
#    languageName = "gb"

#[languages.fr]
#    weight = 2
#    languageName = "fr"

#[languages.fr.params]
#    description = "Le DevFest, ou 'Developers Festival', est une conférence technique destinée aux développeurs. Elle s'adresse aussi bien aux étudiants, aux professionnels ou tout simplement aux curieux technophiles."

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false